import 'package:flutter/cupertino.dart';
import 'package:get/get.dart';

class LocalString extends Translations
{

  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys =>
      {
        'En': {
          'Skip' :'Skip',
          'Search Food Products': "Search Food Products",
          'Search food by Product name to know what allergy types it contains':'Search food by Product name to know what allergy types it contains' ,
          'Search Recipes & Menus' : 'Search Recipes & Menus',
          'Search different recipes that are safe to your allergy type, and you can also see the allergens Menus of the most popular restaurants' : 'Search different recipes that are safe to your allergy type, and you can also see the allergens Menus of the most popular restaurants',
          'Scan, Check & Enjoy!' : 'Scan, Check & Enjoy!',
          'Scan products you want to check if they are Allergy free or Alcohol free & enjoy happy, friendly Shopping!' : 'Scan products you want to check if they are Allergy free or Alcohol free & enjoy happy, friendly Shopping!',
          'Login Account': 'Login Account',
          'Email':'Email',
          'Password':'Password',
          'Forget Password?':'Forget Password?',
          'Login':'Login',
          'Not registered yet?': 'Not registered yet?',
          'Enter your password':'Enter your password',
          "Password can't be empty": "Password can't be empty",
          "Email can't be empty" : "Email can't be empty",
          "Enter your email":"Enter your email",
          "Create Account": "Create Account",
          "Username":"Username",
          "Email":"Email",
          "Password":"Password",
          "Enter your name": "Enter your name",
          "Must be at least 8 characters, contain at least 1 number" : "Must be at least 8 characters, contain at least 1 number",
          "Already have an account?" : "Already have an account?",
          "Username can't be empty":"Username can't be empty",

          "Profile":"Profile",
          "Knowledge":"Knowledge",
          "Logout":"Logout",
          "Home":"Home",
          "Categories":"Categories",
          "Menus":"Menus",
          "Recipes":"Recipes",

          'Logout?':'Logout?',
          'Are you sure want to logout?':'Are you sure want to logout?',
          'Cancel':'Cancel',

          'Search Restaurant': 'Search Restaurant',
          'Search recipe': 'Search recipe',
          'Search product': 'Search product',
          'Snacks': 'Snacks',
          'Protein':'Protein',
          'Milk':'Milk',
          'Bakery':'Bakery',
          'Allergen Menu': 'Allergen Menu',
          'Duration:':'Duration:',
          'Ingredients':'Ingredients',
          'Directions':'Directions',
          'Allergy contained':'Allergy contained',
          'Contains':'Contains',
          "Edit Account":"Edit Account",

          "Edit Allergies":"Edit Allergies",
          "Update" : "Update",
          "Edit email":"Edit email",
          "Edit username":"Edit username",

          "Search Knowledge": "Search Knowledge",

          "Strawberry" : "Strawberry",
          "EggYolk":"EggYolk",
          "EggWhite":"EggWhite",
          "Fish":"Fish",
          "Egg":"Egg",
          "Peanut":"Peanut",
          "Nut":"Nut",
          "Corn":"Corn",
          "MilkCasein":"MilkCasein",
          "MilkWhey":"MilkWhey",
          "Soy":"Soy",
          "Wheat":"Wheat",
          "Gluten":"Gluten",
          "Almond":"Almond",
          "Crustacean":"Crustacean",
          "Save":"Save",
          'Please, select your food allergy/ies':"Please, select your food allergy/ies",

          'Check on it!':'Check on it!',
          'What do you want to detect?':'What do you want to detect?',
          'Alcohol Detection':'Alcohol Detection',
          'Allergy Detection':'Allergy Detection',
          'Detect Alcohol!': 'Detect Alcohol!',
          'Gallery':'Gallery',
          'Camera':'Camera',
          'Detect Allergy!': 'Detect Allergy!',
          'Groups':'Groups',
          "You've not joined any groups, tap on the add icon to create a group or also search from top search button.":"You've not joined any groups, tap on the add icon to create a group or also search from top search button.",
          "Search groups":"Search groups",
          "Admin:":"Admin:",
          "Join Now":"Join Now",
          "Joined":"Joined",
          "Send a message":"Send a message",
          "Group Info": "Group Info",
          "Exit":"Exit",

          "Are you sure you exit the group?":"Are you sure you exit the group?",
          "Left the group":"Left the group",
          "Successfully joined the group": "Successfully joined the group",
          "Join the conversation": "Join the conversation",

          "Scan":"Scan",
          'Search':'Search',
          "NO MEMBERS":"NO MEMBERS",
          "Group:":"Group",
          "Full Name":"Full Name",

          "Are you sure you want to logout?":"Are you sure you want to logout?",
          "Forgot Your Password?": "Forgot Your Password?",
          "Reset Password": "Reset Password",
          "check your email":"check your email",
          'Email not found. Please try again.':'Email not found. Please try again.',
          "Password must be at least 8 characters and contain at least 1 number":"Password must be at least 8 characters and contain at least 1 number",
          "Password must be at least 8 characters":"Password must be at least 8 characters",
          "Password must contain at least 1 number":"Password must contain at least 1 number",

          "Change Language":"Change Language",
          "Alcohol Detected!":"Alcohol Detected!",
          "OK":"OK",
        },

        'Ar':
        {
          'Skip' :'تخطى',
          'Search Food Products': "بحث عن المنتجات الغذائية",
          'Search food by Product name to know what allergy types it contains':'ابحث عن الطعام باسم المنتج لمعرفة أنواع الحساسية التي يحتوي عليها' ,
          'Search Recipes & Menus' : 'تصفح الوصفات و المنيو',
          'Search different recipes that are safe to your allergy type, and you can also see the allergens Menus of the most popular restaurants' :
          'بحث عن الوصفات المختلفة الآمنة لنوع الحساسية لديك ، ويمكنك أيضًا الاطلاع على قوائم المواد المسببة للحساسية في المطاعم الأكثر شهرة',
          'Scan, Check & Enjoy!' : 'امسح ، تحقق واستمتع!',
          'Scan products you want to check if they are Allergy free or Alcohol free & enjoy happy, friendly Shopping!' :
          'قم بمسح المنتجات التي تريد التحقق مما إذا كانت خالية من مسببات الحساسية أو خالية من الكحول واستمتع بالتسوق السعيد والودي!',

          'Login Account': 'حساب تسجيل الدخول',
          'Email':'البريد الإلكتروني',
          'Password':'كلمة المرور',
          'Forget Password?':'نسيت كلمة المرور؟',
          'Login':'دخول',
          'Not registered yet?':'ليس لديك حساب بعد؟',
          'Sign up':'تسجيل حساب',
          'Enter your password':'أدخل كلمة المرور الخاصة بك هنا',
          "Password can't be empty" : "كلمة المرور لا يمكن أن تكون فارغة",
          "Email can't be empty":"لا يجوز أن يكون البريد الإلكتروني فارغًا",
          "Enter your email":"أدخل بريدك الإلكتروني",

          "Create Account": "إنشاء حساب",
          "Username":"اسم المستخدم",
          "Email":"البريد الإلكتروني",
          "Password":"كلمة المرور",
          "Enter your name": "أدخل اسمك",
          "Must be at least 8 characters,contain at least 1 number" :
          "يجب أن يتكون من 8 أحرف على الأقل ، وأن يحتوي على رقم واحد على الأقل",
          "Already have an account?" : "هل لديك حساب؟",
          "Username can't be empty":"اسم المستخدم لا يمكن أن يكون فارغا",

          "Profile":"الصفحة الشخصية",
          "Knowledge":"المعرفة",
          "Logout":"تسجيل الخروج",
          "Home":"الصفحة الرئيسية",
          "Categories":"المنتجات",
          "Menus":"المنيو",
          "Recipes":"الوصفات",

          'Logout?':'تسجيل الخروج؟',
          'Are you sure want to logout?':'هل أنت متأكد من من رغبتك في الخروج؟',
          'Cancel':'إلغاء',

          'Search Restaurant': 'ابحث عن مطعم',
          'Search recipe': 'ابحث عن وصفة',
          'Search product': 'ابحث عن منتج',
          'Snacks': 'وجبات خفيفة',
          'Protein':'بروتين',
          'Milk':'حليب',
          'Bakery':'مخبز',
          'Allergen Menu': 'قائمة مسببات الحساسية',
          'Duration:':'المدة الزمنية:',
          'Ingredients':'المكونات',
          'Directions':'الخطوات',
          'Allergy contained':'يحتوي علي حساسية',
          'Contains':'يحتوي علي',
          "Edit Account" : 'تعديل الحساب',

          "Edit Allergies":"تعديل الحساسية",
          "Update" : "تحديث",

          "Edit email":"تعديل البريد الإلكتروني",
          "Edit username":"تعديل اسم المستخدم",
          "Search Knowledge":"البحث في المعرفة",

          "Strawberry" : "الفراولة",
          "EggYolk":"صفار البيض",
          "EggWhite":"بياض البيض",
          "Fish":"السمك",
          "Egg":"البيض",
          "Peanut":"فول سوداني",
          "Nut":"الجوز",
          "Corn":"الذرة",
          "MilkCasein":"كازين اللبن ",
          "MilkWhey":"مصل اللبن",
          "Soy":"فول الصويا",
          "Wheat":"القمح",
          "Gluten":"جلوتين",
          "Almond":"لوز",
          "Crustacean":"القشريات",
          "Save":"حفظ",
          'Please, select your food allergy/ies':"من فضلك ، حدد حساسية الطعام التي تعاني منها ",

          'Check on it!':'تحقق من ذلك',
          'What do you want to detect?':'ماذا تريد أن تكتشف؟',
          'Alcohol Detection':'كشف الكحول',
          'Allergy Detection':'كشف الحساسية',
          'Detect Alcohol!': 'كشف الكحول!',
          'Gallery':'معرض',
          'Camera':'الكاميرا',
          'Search':'بحث',
          'Detect Allergy!': 'الكشف عن الحساسية!',
          'Groups':'المجموعات',
          "You've not joined any groups, tap on the add icon to create a group or also search from top search button.":
          "لم تنضم إلى أي مجموعات ، انقر على أيقونة الإضافة لإنشاء مجموعة أو ابحث أيضًا من زر البحث العلوي",
          "Search groups":"ابحث عن مجموعة",
          "Admin:":"المسؤول:",
          "Join Now":"انضم الآن",
          "Joined":"تم الانضمام",
          "Send a message":"إرسال رسالة",
          "Group Info": "معلومات المجموعة",
          "Exit":"خروج",
          "Are you sure you exit the group?":"هل أنت متأكد من خروجك من المجموعة؟",
          "Left the group":"غادر المجموعة",
          "Successfully joined the group": "تم الانضمام إلى المجموعة بنجاح",
          "Join the conversation": "انضم إلى المحادثة",
          "Scan":"فحص المكونات",

          "NO MEMBERS":"لا يوجد أعضاء",
          "Full Name":"الاسم كامل",
          "Group:": " مجموعة:",

          "Are you sure you want to logout?":"هل أنت متأكد أنك تريد تسجيل الخروج؟",
          "Forgot Your Password?": "هل نسيت كلمة المرور؟",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "check your email":"تحقق من بريدك الإلكتروني",
          'Email not found. Please try again.':"البريد الإلكتروني غير موجود. يرجى المحاولة مرة أخرى.",
          "Password must be at least 8 characters and contain at least 1 number":
          "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل وتحتوي على رقم واحد على الأقل",
          "Password must be at least 8 characters":"يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
          "Password must contain at least 1 number":"يجب أن تحتوي كلمة المرور على رقم واحد على الأقل",
          "Change Language":"تغيير اللغة",

          "Alcohol Detected!":"يحتوي علي كحول!",
          "OK":"حسنا",
        },

      };

}